## Pandas -- Data Frame and series

In [ ]:
pip install pandas

In [3]:
import pandas as pd

In [ ]:
## series - 1 dimesnion tabular data

## create a series from a list

data=[1,2,3,4,5]
series=pd.Series(data)
series
print(type(series))

In [ ]:
## create a series from a dict
a={"a":12,"b":13,"c":15}
series_dict=pd.Series(a)
series_dict

In [ ]:
data=[1,2,3,4,5]
index= ["a","b","c","d","e"]

s=pd.Series(data,index=index)

In [ ]:
# Data Frame - multiple rows and column

# create a DF from of a dict of list

data={
    "name":["Chandra","john","jack"],
    "age": [12,17,20],
    "city":["bng",'texas',"delhi"]
}
df=pd.DataFrame(data)
df

In [ ]:
## create df from list of dict

data={
    {"name":["Chandra","john","jack"]},
    "age": [12,17,20],
    "city":["bng",'texas',"delhi"]
}

In [4]:
df=pd.read_csv('/kaggle/input/datasets/chandrasekharsahu17/data-csv/data.csv')

In [ ]:
df.head()

In [ ]:
## Row Index

df.loc[0]

In [ ]:
# column index 

df.iloc[0]

In [ ]:
df.loc[0][0]

In [ ]:
## accessing specified element

df["Region"].unique()

In [ ]:
df.at[2,'Sales']

In [ ]:
df.iat[2,2]

In [ ]:
# Data Manipuklation in DF

df['Salary']=400

In [ ]:
df.head()

In [ ]:
df.drop('Salary',axis=1,inplace=True)

In [ ]:
df.head()

In [ ]:
df['Sales']=df["Sales"]+50

In [2]:
df.head()

NameError: name 'df' is not defined

In [ ]:
df.drop(3,inplace=True)

In [ ]:
df.describe()

In [5]:
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [6]:
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [8]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [19]:
## handelling missuing values

df.isnull().sum()

Date            0
Category        0
Value           3
Product         0
Sales           4
Region          0
fill_salesNa    0
dtype: int64

In [11]:
df_filled=df.fillna(0)

In [17]:
df["fill_salesNa"]=df['Sales'].fillna(df['Sales'].mean())

In [18]:
df.head(5)

         Date Category  Value   Product  Sales Region  fill_salesNa
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0

In [26]:
## Renaming column
## rename should be done in key value pair 

df=df.rename(columns={"Date":"Sale Date"})

df.head()

    Sale Date Category  Value   Product  Sales Region  fill_salesNa
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0